
GET http://localhost:5122/api/program/history

//GET http://localhost:5100/api/programs

# POST /api/events
# POST /api/events

// POST http://localhost:5100/api/event
// Content-Type: application/json

// {
//   "eventName": "Sample Event",
//   "eventLocation": "Sample Location",
//   "eventDate": "2023-01-01",
//   "startTime": "12:00:00",
//   "endTime": "11:00:00",
//   "recurring": false,
//   "administrators": "admin@example.com",
//   "eventHeaderImage": "url/to/event-image.jpg",
//   "eventDescription": "Sample event description",
//   "tags": "tag1"
