



POST http://localhost:3001/programs
Content-Type: application/json

{
  "name": "program",
  "description": "This is a science program",
  "headerImage": "URL_to_header_image",
  "color": "#FFFFFF",
  "tags": ["Undergraduate", "Graduate"],
  "adminemail" : "mario@uci"
}

###
POST http://localhost:3001/events
Content-Type: application/json

{
    "name": "Event",
    "location": "Sample Location",
    "date": "2024-02-11",
    "start_time": "14:30",
    "end_time": "15:30",
    "recurring": ["Monthly"],
    "recurring_ends": "2024-02-25",
    "user_emailaddress": "mario@uci",
    "description": "Sample description",
    "headerimage": "URL_to_header_image",
    "tags": ["Undergraduate"]
}


